name: Tidy-HTML-Files
run-name: ${{ github.actor }} is Cleaning the HTML files
on: [push]
jobs:
    tidy-html-files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout
            - run: sudo apt install tidy
            - run: echo Tidy Installed
            - run: tidy -v
            - run: tidy *.html > tidy-html.log
