name: Tidy-HTML-Files
run-name: ${{ github.actor }} is Editing Commits
on: [push]
jobs:
    master:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@main
            - name: Formating Websites
              run: |
                  sudo apt install tidy
                  echo Tidy Installed
                  touch tidy.log
                  tidy -v > tidy.log
                  tidy -mi *.html >> tidy.log || true
                  tidy -mi *.js >> tidy.log || true
                  tidy -mi *.css >> tidy.log || true
                  tidy -mi */*.html >> tidy.log || true
                  tidy -mi */*.js >> tidy.log || true
                  tidy -mi */*.css >> tidy.log || true
                  tidy -mi */*/*.html >> tidy.log || true
                  tidy -mi */*/*.js >> tidy.log || true
                  tidy -mi */*/*.css >> tidy.log || true
            - name: Making Commit Log
              run: |
                  echo Next Commit >> commit.log
                  ls -a >> commit.log
            - name: Commit changes
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "GitHub Actions"
                  git add tidy.log commit.log *.html *.js *.css */*.html */*.js */*.css */*/*.html */*/*.js */*/*.css
                  git commit -m "Tidy Formatting"
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
