name: PUSH-JOBS
run-name: ${{ github.actor }} is Editing Commits
on: [push]
jobs:
    master:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Checkout Repository
              uses: actions/checkout@main
            - name: Making Commit Log
              run: |
                  echo Next Commit >> commit.log
                  ls -a >> commit.log
            - name: Commit changes
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "GitHub Actions"
                  git add commit.log
                  git commit -m "Push Actions"
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
