name: Build Blog JSON

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get list of Files
              run: |
                  files=($(ls))
                  json_array=()
                  for file in "${files[@]}"
                  do
                    date_string=$(grep -E '^date: ' "$file" | cut -d' ' -f2)
                    # Use the date command to extract the year, month, and date
                    year=$(date -d "$date_string" +%Y)
                    month=$(date -d "$date_string" +%m)
                    day=$(date -d "$date_string" +%d)
                    json_array+=($(echo "{\"file\":\"$file\",\"date\":\"$date_string\",\"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\"}"))
                  done
                  echo "[$(IFS=,; echo "${json_array[*]}" | jq -s -c 'sort_by(.date)')]" > files.json

            - name: Remove trailing comma
              run: |
                  sed -i '$ s/,$//' files.json

            - name: Commit changes
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "GitHub Actions"
                  git add files.json
                  git commit -m "Update files.json"
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
